#ifndef LEXER_H
#define LEXER_H

#include "stdbool.h"
#include "stdint.h"
#include "../utils.h"
#include "string.h"

#ifdef DEBUG
#define PRINT_TOKEN(t) printf("[%s:%d] tok(len=%d): %.*s\n", \
    t->location.path_name, t->location.line_number, t->len, \
    t->len, t->start)
#endif

typedef enum {
    TOK_SPECIAL_START,
    TOK_EOF = TOK_SPECIAL_START,
    TOK_ERR,
    TOK_DOTS3, // ...
    TOK_SPECIAL_END,

    TOK_NUM = TOK_SPECIAL_END,
    TOK_IDENT,

    TOK_SEPARATOR_START,
    TOK_COLON = TOK_SEPARATOR_START,
    TOK_SEMICOLON,
    TOK_DOT,
    TOK_COMMA,
    TOK_LPAREN,
    TOK_RPAREN,
    TOK_LSQUARE,
    TOK_RSQUARE,
    TOK_LBRACE,
    TOK_RBRACE,
    TOK_SEPARATOR_END,

    TOK_OPERATOR_START,
    TOK_HASHTAG = TOK_OPERATOR_START,
    TOK_HASHTAG_HASHTAG,
    TOK_COLON_EQUAL,
    TOK_PLUS,
    TOK_PLUS_PLUS,
    TOK_PLUS_EQUAL,
    TOK_MINUS,
    TOK_MINUS_MINUS,
    TOK_MINUS_EQUAL,
    TOK_STAR,
    TOK_STAR_EQUAL,
    TOK_SLASH,
    TOK_SLASH_EQUAL,
    TOK_SHR,
    TOK_SHR_EQUAL,
    TOK_SHL,
    TOK_SHL_EQUAL,
    TOK_ROL,
    TOK_ROL_EQUAL,
    TOK_ROR,
    TOK_ROR_EQUAL,
    TOK_AND,
    TOK_AND_AND,
    TOK_AND_EQUAL,
    TOK_OR,
    TOK_OR_OR,
    TOK_OR_EQUAL,
    TOK_XOR,
    TOK_XOR_EQUAL,
    TOK_TILDE,
    TOK_BANG,
    TOK_BANG_EQUAL,
    TOK_EQUAL,
    TOK_EQUAL_EQUAL,
    TOK_GREATER,
    TOK_GREATER_EQUAL,
    TOK_LESS,
    TOK_LESS_EQUAL,
    TOK_PERCENT,
    TOK_PERCENT_EQUAL,
    TOK_OPERATOR_END,

    TOK_SYMBOL_START,
    TOK_COMMERCIAL_AT = TOK_SYMBOL_START,
    TOK_DOLLAR,
    TOK_SYMBOL_END,

    TOK_KEYWORD_START,
    TOK_IF = TOK_KEYWORD_START,
    TOK_ELSE,
    TOK_JMP,
    TOK_CALL,
    TOK_HLT,
    TOK_NOP,
    TOK_USE,
    TOK_UNUSE,
    TOK_LIMIT,
    TOK_INT,
    TOK_FLAGS,
    TOK_LAYOUT,
    TOK_BITSET,
    TOK_ALL,
    TOK_AS,
    TOK_SP,
    TOK_SIZEOF,
    TOK_RESERVE,
    TOK_RETURN,
    TOK_ALIGNED,
    TOK_DELETE,
    TOK_KEYWORD_END,
} token_type;

typedef struct {
    bool new_line; // The tok is on a new line
    int line_number;
    char *line_start;
    const char *path_name;
} token_location;
typedef struct token token;
struct token {
    char *start;
    int len;

    token_type type;
    int64_t number;

    token *src; // Used when a tok is expanded from another (preprocessor)
    bool generated; // Used when is generated by the preprocessor
    token_location location;
};

typedef struct {
    char *source;
    char *currch;
    token *currtok;

    bool error_occured;
    bool run;

    token_location location;
} lexer_ctx;

typedef struct {
    vector tokens;
    size_t pos;
    bool error_occured;

    token_location *last_location;
} token_stream;

typedef struct {
    char *path_name;
    char *content;
} source_file;
source_file *file_new(vector *files, char *path_name);
bool lex(source_file *file, vector *tokens);

token *advance_token(token_stream *stream);
token *consume_token(token_type type, char *errmsg, token_stream *stream);
token *match_token(token_type type, token_stream *stream);

static inline token *current_token(token_stream *stream) {
    return (token *)vector_get(&stream->tokens, stream->pos);
}
static inline token *take_token(token_stream *stream) {
    token *tok = current_token(stream);
    advance_token(stream);
    return tok;
}

static inline token *next_token(token_stream *stream) {
    if (stream->pos >= stream->tokens.count) {
        return current_token(stream);
    }
    return (token *)vector_get(&stream->tokens, stream->pos + 1);
}
static inline token *prev_token(token_stream *stream) {
    if (stream->pos == 0) {
        return current_token(stream);
    }
    return (token*)vector_get(&stream->tokens, stream->pos - 1);
}
static inline bool at_end(token_stream *stream) {
    if (stream->tokens.count > 0)
        return stream->pos >= stream->tokens.count - 1;
    return true;
}
static inline bool token_is_str(token *tok, const char *str) {
    int len = strlen(str);
    return tok->type == TOK_IDENT && tok->len == len && strncmp(tok->start, str, len) == 0;
}
static inline bool token_is_chr(token *tok, char ch) {
    return tok->len == 1 && *tok->start == ch;
}
static inline bool tokens_equal(token *t1, token *t2) {
    return (t1->len == t2->len) && strncmp(t1->start, t2->start, t1->len) == 0;
}

#define EXPECT(stream, msg, ...) \
    report(current_token(stream), DIAGNOSTIC_ERROR, true, stream, msg, ##__VA_ARGS__)
#define EXPECT_PREV(stream, msg, ...) \
    report(prev_token(stream), DIAGNOSTIC_ERROR, true, stream, msg, ##__VA_ARGS__)
#define EXPECT_AT(tok, stream, msg, ...) \
    report(tok, DIAGNOSTIC_ERROR, true, stream, msg, ##__VA_ARGS__)
#define ERROR_AT(tok, stream, msg, ...) \
    report(tok, DIAGNOSTIC_ERROR, false, stream, msg, ##__VA_ARGS__)
#define ERROR(stream, msg, ...) ERROR_AT(current_token(stream), stream, msg, ##__VA_ARGS__)

typedef enum {
    DIAGNOSTIC_NOTE,
    DIAGNOSTIC_WARNING,
    DIAGNOSTIC_ERROR
} diagnostic_level;
void report(token *tok, diagnostic_level level, bool underline_carret, token_stream *stream, char *fmt, ...);

void stream_print(token_stream *stream);

static inline void source_free(source_file *file) {
    my_free(file->path_name);
    my_free(file->content);
    my_free(file);
}
void stream_free(token_stream *stream);

#endif